Create hashmap_copy.h
ALILILILILI-KHAN/HashMap-Code-Review pull request #1
Opened 2021-03-05 11:35 UTC by ALILILILILI-KHAN

Класс хэштаблицы. Зиманов Алихан, 201-2. Длинный контест 3 - задача A. [https://official.contest.yandex.ru/contest/24924/run-report/48901613/](Посылка).

2021-04-14 11:27 UTC, sartuhin requested changes

2021-04-14 11:27 UTC, sartuhin commented on hashmap_copy.h
> +    typename std::list<my_pair>::iterator endIterator;
my_pair и endIterator это добавленные типы, но почему они называются в разном стиле?

2021-04-14 11:27 UTC, sartuhin commented on hashmap_copy.h
> +        size_t bucketId;
Тоже разные стили названия внутренних переменных.

2021-04-22 15:36 UTC, ALILILILILI-KHAN commented on hashmap_copy.h
> +    typename std::list<my_pair>::iterator endIterator;
Вроде всё исправил

2021-04-22 15:48 UTC, sartuhin approved these changes

2021-04-25 10:23 UTC, merged